### PR TITLE
🦋 Fix bug: slice bounds out of range

### LINKED ISSUE #17: Should GetSelection panic or return nil?
`GetSelection` function returns `*Bucket`, but in case of internal errors it can panic. For example if there is a `Select` rule bigger than available `*Bucket`

```go
func TestBucket_RuntimeError(t *testing.T) {
	g := NewGomegaWithT(t)
	buckets := []bucket{
		{"/Location:Europe/Country:Spain/City:Madrid", []uint32{17, 18}},
	}
	root, err := newRoot(buckets...)
	g.Expect(err).NotTo(HaveOccurred())

	ss := []Select{
		{Key: NodesBucket, Count: 3}, // available only two
	}

	r := root.GetSelection(ss, defaultPivot)
	g.Expect(r).NotTo(BeNil())
}
```

This code leads to panic
```
=== RUN   TestBucket_RuntimeError
--- FAIL: TestBucket_RuntimeError (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range
```

In our code we avoid this case by calling `GetMaxSelection` in advance. This function returns error if something goes wrong. But in general I don't know whether is it correct behaviour for `GetSelection` function to panic.

### PR DESCRIPTION
**Pull request by im-kulikov**
fix #17

### CODE REVIEW

File: policy_test.go [hunk 1]
```diff
@@ -27,19 +27,39 @@ func newRoot(bs ...bucket) (b Bucket, err error) {
...
+		}
+		root, err := newRoot(buckets...)
+		g.Expect(err).NotTo(HaveOccurred())
+
+		ss := []Select{
+			{Key: "Location", Count: 1},
+			{Key: NodesBucket, Count: 3},
+		}
+
+		r := root.GetSelection(ss, defaultPivot)
```
Comment (fyrchik) [inline policy_test.go]: add `g.Expect(r).NotTo(BeNil())`, please
